In [46]:
import numpy as np

In [47]:
#create a 1-dimensional array
a1 = np.array([1])
a1,a1.shape

(array([1]), (1,))

In [48]:
#2 - Create a 2 - dimensional array 
a2 = np.array([[1, 2, 3],
                [4, 5, 6]])
a2.shape

(2, 3)

In [49]:
# Create a 3 - dimensional array
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]]])
a3, a3.shape

(array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]),
 (1, 3, 3))

In [50]:
##Atributos da matriz 1 (shape, numero de dimensoes, datatype, size and type)
a1.shape#linha 1,coluna0

(1,)

In [51]:
a1.size

1

In [52]:
a2.dtype

dtype('int32')

In [58]:
import pandas as pd
#passando os arrays
a1 = pd.DataFrame(a1)
a2 = pd.DataFrame(a2)
#a3 = pd.DataFrame(a3)

In [54]:
a4= np.ones((10,2))
a4

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [55]:
a5 = np.zeros(((7,2,3)))
a5

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [56]:
#Create a array within a range of 0 and 100 with step3
a5 = np.arange(0,100,3)
a5

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [57]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a5 = np.random.randint(0,10, size = (7,2))
a5

array([[9, 4],
       [3, 9],
       [5, 6],
       [1, 9],
       [2, 0],
       [1, 1],
       [7, 0]])

In [60]:
 
# Create a random array of floats between 0 & 1 of shape (3, 5)
a6 = np.random.random( size = (3,5)) 
a6

array([[0.82814124, 0.79836773, 0.28066192, 0.64629991, 0.23088092],
       [0.15804891, 0.7556432 , 0.58288644, 0.07269647, 0.17014205],
       [0.90425807, 0.63020415, 0.92755284, 0.11015434, 0.32352147]])

In [65]:
## Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.seed(42)
a7 = np.random.randint(10, size = (4,6))
a7

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [66]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a8 = np.random.randint(10, size = (3,7))
a8

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6],
       [1, 3, 8, 1, 9, 8, 9]])

In [68]:
# Find the unique numbers in the array you just created
a8_unique = np.unique(a8)
a8_unique

array([0, 1, 2, 3, 4, 6, 8, 9])

In [74]:
# Find the 0'th index of the latest array you created
a8[0]

array([8, 0, 9, 2, 6, 3, 8])

In [76]:
a8[:2]


array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [77]:
# Get the first 2 values of the first 2 rows of the latest array
a8[:2,:2]

array([[8, 0],
       [2, 4]])

In [78]:
a9 = np.random.randint(10, size = (3,5))
a_ones = np.ones((3,5))

In [80]:
#Add the two arrays together
a9 + a_ones

array([[ 5.,  2.,  4.,  7.,  8.],
       [ 3.,  1.,  4.,  2.,  8.],
       [ 4.,  2.,  6.,  6., 10.]])

In [83]:
a9 - a_ones

array([[ 3.,  0.,  2.,  5.,  6.],
       [ 1., -1.,  2.,  0.,  6.],
       [ 2.,  0.,  4.,  4.,  8.]])