## 2.0 Creating arrays

In [134]:
import numpy as np
import pandas as pd

In [135]:
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [136]:
#tipo do array
simple_array.dtype

dtype('int32')

In [137]:
#Criando um array onde todas as suas posições os valores sao 1
ones = np.ones((2,3 ))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [138]:
#Criando um array onde todos os indices sao zeros
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [139]:
#Criando um array com um intevalo
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [140]:
#Criando um vetor com numeros inteiros aleatorios
random_array = np.random.randint(0,10,size = (3,5)) #Inicio, fim, dimensão do vetor
random_array

array([[4, 3, 9, 7, 1],
       [5, 8, 8, 1, 3],
       [8, 8, 0, 3, 9]])

In [141]:
#Tamanho do vetor
random_array.size

15

In [142]:
#Dimensão do vetor
random_array.shape

(3, 5)

In [143]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.62261493, 0.21998622, 0.00107923],
       [0.24745427, 0.75170421, 0.21750013],
       [0.43162277, 0.47211389, 0.66099854],
       [0.69190017, 0.53511722, 0.63167987],
       [0.89059564, 0.1336564 , 0.75056332]])

In [144]:
random_array2.size

15

In [145]:
random_array2.shape

(5, 3)

 Esta linha define a semente (seed) para o gerador de números pseudo-aleatórios do NumPy. A semente é um valor inicial usado para iniciar o gerador de números aleatórios, garantindo que, se a mesma semente for usada, os mesmos números pseudo-aleatórios serão gerados. Portanto, ao definir a semente como 0, estamos garantindo que, independentemente de quantas vezes executemos o código, obteremos os mesmos números pseudo-aleatórios.

In [146]:
#Pseudo random numbers
# Onde voce consgue numeros deterministicos no vetor, a partir de uma conta
np.random.seed(seed = 0)
random_array4 = np.random.randint(10,size=(5,3))
random_array4

#A

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [147]:
random_array4.shape

(5, 3)

## 3.Viewing arrays and matrices

In [148]:
np.random.seed(seed = 99999)
random_array4 = np.random.randint(10, size = (5,3))
random_array4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [149]:
np.unique(random_array4)
#Retorna apenas valores unicos

array([0, 1, 3, 4, 5, 6, 8, 9])

In [150]:
a1 = np.array([1, 2, 3])

In [151]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6]])

In [152]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]]])

In [153]:
a1

array([1, 2, 3])

In [154]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6. ]])

In [155]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [156]:
a3[:2, :2, :2]  #Tudo até o indicie 2, lembrando que começa em 0

array([[[1, 2],
        [4, 5]]])

In [157]:
a4 = np.random.randint(10, size = (2,3,4,5))
a4

array([[[[2, 0, 0, 5, 0],
         [0, 8, 1, 0, 9],
         [7, 1, 8, 9, 5],
         [8, 3, 4, 2, 1]],

        [[5, 5, 8, 3, 4],
         [6, 9, 6, 9, 4],
         [6, 5, 5, 8, 8],
         [7, 4, 0, 9, 2]],

        [[0, 7, 2, 8, 1],
         [2, 9, 4, 4, 4],
         [3, 3, 4, 1, 0],
         [1, 3, 0, 5, 8]]],


       [[[7, 7, 5, 4, 6],
         [8, 7, 6, 4, 7],
         [4, 4, 4, 2, 5],
         [7, 2, 2, 0, 8]],

        [[1, 5, 5, 5, 6],
         [9, 0, 7, 7, 6],
         [2, 5, 0, 9, 1],
         [0, 6, 9, 9, 3]],

        [[2, 3, 2, 4, 0],
         [6, 0, 2, 0, 6],
         [9, 5, 4, 1, 7],
         [5, 7, 8, 2, 7]]]])

In [158]:
a4[:,:,:,:1]#Nesse caso como o nosso array ele é gerado aleatormianete, nos colocamso com base na dimensao de cada array

array([[[[2],
         [0],
         [7],
         [8]],

        [[5],
         [6],
         [6],
         [7]],

        [[0],
         [2],
         [3],
         [1]]],


       [[[7],
         [8],
         [4],
         [7]],

        [[1],
         [9],
         [2],
         [0]],

        [[2],
         [6],
         [9],
         [5]]]])

## 4.manipulating and comparing arrays

### Arithmetic

In [159]:
a1

array([1, 2, 3])

In [160]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [161]:
# soma
a1 + ones
#diferença
a1 - ones
#multiplicação 
a1 * ones

array([1., 2., 3.])

In [162]:
a2, a1

(array([[1. , 2. , 3.3],
        [4. , 5. , 6. ]]),
 array([1, 2, 3]))

In [163]:
a1 * a2 #muiltiplica linha de a1 por linha de a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 18. ]])

In [164]:
#a3*a2 Vai dar  erro pois sao matrizes de dimensoes diferentes, logo devemos aplicar reshape nela
#logo temos que fazer o reshape da matriz
a2 = a2.reshape(1,2,3)
a2 * a3

ValueError: operands could not be broadcast together with shapes (1,2,3) (1,3,3) 

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

### Agregação
Agregation = performing the same operation on a number of things

In [ ]:
listy_list = [1,2,3]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
type(a1)

In [ ]:
# Use python methods (sum()) on pyhton datatypes and use numpy's methods on numpy arrays(np.sum())

In [ ]:
#Creative a massive NumPy array
massive_array = np.random.random(100000)
massive_array[:10], massive_array.size

In [ ]:
##%timeit serve para quando quisermos calcular o tempo de execução de um programa
%timeit sum(massive_array)
%timeit np.sum(massive_array)
#no caso, é muito mais rapido para a maquina rodar com o numpy

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
np.std(a2)#Calcula o(Standard deviation) desvio padrão de um array numerico
#Se o desvio padrão for baixo, isso significa que os valores estão próximos da média; se for alto, significa que os valores estão mais dispersos.


In [ ]:
#calcular a variancia = measuere of the average degree to witch each number is different to the mean
#Higher varience = wider range of numbers -> maior significa uma gama mais ampla de números
#Lower variance = lower range of number ->enquanto uma variância menor significa uma faixa mais estreita de números
np.var(a2)

In [ ]:
#Standart deviation = squareroot of variance
np.sqrt(np.var(a2))

## std(standard deviation) and var

In [ ]:
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([2,4,6,8,10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

## Reshape and transpost

### Remodelar e transpor

In [ ]:
a2

In [ ]:
a2 = a2.reshape(2,3)

In [ ]:
a2.shape

In [ ]:
a3. shape

In [ ]:
a2 * a3

In [ ]:
#Vamos fazer o sehpae de a2
a2 = a2.reshape(2,3,1) # a sima de cada dimensao deve ser igual oo size do vetor, caso nao seja, ira dar erro
a2

In [ ]:
a2 * a3

In [ ]:
#Transpose
a2

In [ ]:
a2.T # inverte/troca as dimensoes

In [ ]:
a2.T.shape

In [ ]:
a2.shape

## DOT PRODUCT X ELEMENT WISE

### DOT PRODUCT -> PRODUTO ESCALAR
é calculado atraves de uma soma començando em i, sua operação é ai*bi

In [ ]:
np.random.seed(0)
mat1 = np.random.randint(10, size = (5,3))
mat2 = np.random.randint(10, size = (5,3))
mat1

In [ ]:
mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
mat1 * mat2

In [ ]:
#Element- wise multiplication (Hadamard product)

A operação "element-wise" (por elemento) é uma operação que é aplicada a cada elemento
correspondente de dois ou mais arrays, resultando em um novo array com o mesmo tamanho
e forma, onde cada elemento é o resultado da operação aplicada aos elementos 
correspondentes dos arrays de entrada.

"Diferença entre dot product x element wise"

Element wise: nos temos dois vetores de mesma dimensão. onde o resultado será o
a posicão da matriz 1 * posicao matriz 2. Ex 11(mat1) * 11(mat2). O resultado sera uma 
matriz de mesma dimensão das duas .

Dot product = Temos duas matrizes de dimensoes diferentes, no caso suponhamos que
temos uma matriz 3x3 e 3x2. Vamos ter uma matriz de tamanho 3x2, Onde os resultados
serão a primeiro elemento * toda a coluna da 2ºmatriz. 
"https://i.imgur.com/Knd6fXg.png"

In [ ]:
mat1 * mat2

In [ ]:
#Dot product
mat1.shape, mat2.shape

In [ ]:
np.dot(mat1,mat2)

In [ ]:
#Transpose mat1
mat1.T, mat1

In [ ]:
mat1.shape, mat2.T.shape

In [ ]:
mat3 = np.dot(mat1,mat2.T)
mat3

In [ ]:
mat3.shape

### Dot product example(nut butter sales)

In [ ]:
np.random.seed(0)
#number of jars sold -> numero de potes vendidos
sales_amount = np.random.randint(20,size = (5,3))#numero max dos rand, tamanho do array
sales_amount

In [ ]:
#Create weakly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amount, index = ["Mon","Tues","Wed", "Thurs","Fri"],
                                            columns=["Almond Butter","Peanut Butter", "Cashew Butter"])
weekly_sales

In [ ]:
#Create prices array
prices = np.array([10,8,12])
prices

In [ ]:
#Create butterprices Data
butter_prices = pd.DataFrame(prices.reshape(1,3), index = ["Price"], columns = ["Almond Butter","Peanut Butter", "Cashew Butter"])
butter_prices

In [ ]:
total_sales = prices.dot(sales_amount)

In [ ]:
total_sales = prices.dot(sales_amount.T)
total_sales



In [ ]:
#Create daily_sales
butter_prices.shape , weekly_sales.shape

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

In [ ]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

### Comparision arrays

In [ ]:
a1

In [ ]:
a2

In [ ]:
bool_array = a1 >= a2
bool_array

In [ ]:
type(bool_array), bool_array.dtype

In [ ]:
a1 > 5

In [ ]:
a1 < 3

In [ ]:
a1 == a2

### Sorting arrays

In [ ]:
random_array= np.random.randint(10, size = (3,5))
random_array

In [ ]:
random_array.shape

In [ ]:
np.sort(random_array) # Ordena as linhas do vetor

In [165]:
np.argsort(random_array) #Ordena de acordo com os indices

array([[4, 1, 0, 3, 2],
       [3, 4, 0, 1, 2],
       [2, 3, 0, 1, 4]], dtype=int64)

In [166]:
a1

array([1, 2, 3])

In [167]:
np.argmax(a1),np.argmin(a1)

(2, 0)

In [169]:
np.argmax(random_array, axis = 0)
#stá solicitando ao NumPy que encontre os índices dos valores máximos ao longo do eixo 0 (ou seja, ao longo das linhas) do array

array([2, 1, 0, 0, 2], dtype=int64)

In [170]:
np.argmax(random_array, axis = 1)
#encontre os índices dos valores máximos ao longo do eixo 1

array([2, 1, 4], dtype=int64)